service: AzureQueueSend

provider:
  name: azure
  region: West Europe
  runtime: python3.8
  prefix: queuesend
  os: linux 
  stage: dev

functions:
  queue-out:
    handler: queue_out.main
    events:
      - queue: emailQueue
        name: queue
        connection: AzureWebJobsStorage
        accessRights: listen

  queue-in:
    handler: queue_in.main
    events:
      - http: true
        methods:
          - POST
        authLevel: function
        name: request

      - http: true
        direction: out
        name: $return

      - queue: emailQueue
        name: queue
        direction: out
        connection: AzureWebJobsStorage
        accessRights: manage

plugins:
  - serverless-azure-functions
  - serverless-python-requirements
  - serverless-dotenv-plugin

package:
  patterns:
    - 'functions/**'
