service: AzureQueueSend

provider:
  name: azure
  region: West Europe
  runtime: python3.8
  prefix: queuesend
  os: linux 
  stage: dev

functions:
  queue-out:
    handler: queue_out.main
    events:
      - queue: emailQueue
        name: queue
        connection: AzureWebJobsStorage
        accessRights: listen

      # - http: true
      #   direction: out
      #   name: $return
      
      # - sendGrid:
      #     x-azure-settings:
      #       direction: out
      #       apiKey: sendGridKey
      #       name: sendGridMessage
      #       from: konstantin_mokhov@epam.com

  queue-in:
    handler: queue_in.main
    events:
      - http: true
        methods:
          - GET
        authLevel: function
        name: request

      - http: true
        direction: out
        name: $return

      - queue: emailQueue
        name: queue
        direction: out
        connection: AzureWebJobsStorage
        accessRights: manage

plugins:
  - serverless-azure-functions
  - serverless-python-requirements
  - serverless-dotenv-plugin
package:
  patterns:
    - 'functions/**'
